/**
 * CrisisOS — Synthetic Emergency Operations Demo Dataset
 * Serves as operational fallback when database is unconfigured or in serverless environments.
 * Ensures the Command Center and operational screens render completely and reliably.
 */

export const FALLBACK_INCIDENTS = [
  {
    id: "inc-demo-1",
    title: "Mass Casualty Event — Navrangpura",
    description: "Multi-vehicle collision with secondary structural impact near commerce six roads. High victim count.",
    type: "MASS_CASUALTY",
    severity: "CRITICAL",
    status: "REPORTED",
    source: "EMERGENCY_CALL",
    locationName: "Navrangpura, Ahmedabad",
    latitude: 23.0365,
    longitude: 72.5611,
    locationConfidence: 0.95,
    affectedCount: 25,
    injuryCount: 14,
    hazards: JSON.stringify(["Structural Instability", "Fuel Leak", "Traffic Gridlock"]),
    requiredCapabilities: JSON.stringify(["TRAUMA_CARE", "ADVANCED_LIFE_SUPPORT", "PATIENT_TRANSPORT"]),
    language: "en",
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    events: [
      { id: "evt-1", type: "CALL_RECEIVED", description: "911 voice dispatch registered initial report", createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString() },
      { id: "evt-2", type: "TRIAGE_COMPLETED", description: "AI Commander classified priority as CRITICAL", createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString() },
    ],
    assignments: [],
    recommendations: [],
  },
  {
    id: "inc-demo-2",
    title: "Chemical Fire — GIDC Phase 2, Ahmedabad",
    description: "Industrial solvent processing unit fire with toxic chemical vapor cloud releasing southwards.",
    type: "HAZMAT",
    severity: "CRITICAL",
    status: "ASSIGNED",
    source: "IOT_SENSOR",
    locationName: "GIDC Phase 2, Plot 47, Ahmedabad",
    latitude: 22.9567,
    longitude: 72.6342,
    locationConfidence: 0.98,
    affectedCount: 40,
    injuryCount: 8,
    hazards: JSON.stringify(["Toxic Vapor Cloud", "Chemical Explosion Risk", "Corrosive Runoff"]),
    requiredCapabilities: JSON.stringify(["HAZMAT_RESPONSE", "FIRE_SUPPRESSION", "DECONTAMINATION"]),
    language: "en",
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    events: [
      { id: "evt-3", type: "IOT_TRIGGERED", description: "Atmospheric VOC sensor threshold exceeded 450ppm", createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString() },
      { id: "evt-4", type: "STATUS_UPDATE", description: "HAZMAT-01 dispatched under commander authorization", createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
    ],
    assignments: [],
    recommendations: [],
  },
  {
    id: "inc-demo-3",
    title: "Major Flood — Sector 7, Kankaria, Ahmedabad",
    description: "Severe urban flooding along low-lying drainage canal. Water risen 4 feet in last hour. Multiple families trapped on rooftops.",
    type: "FLOOD",
    severity: "CRITICAL",
    status: "VERIFIED",
    source: "EMERGENCY_CALL",
    locationName: "Sector 7, Kankaria, Ahmedabad",
    latitude: 23.0009,
    longitude: 72.6017,
    locationConfidence: 0.90,
    affectedCount: 200,
    injuryCount: 15,
    hazards: JSON.stringify(["Rising Water", "Submerged Cables", "Hypothermia Risk"]),
    requiredCapabilities: JSON.stringify(["WATER_RESCUE", "FLOOD_EVACUATION", "TRAUMA_CARE"]),
    language: "en",
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    events: [
      { id: "evt-5", type: "FIELD_VERIFIED", description: "Patrol unit 02 confirmed 30+ structures submerged", createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
    ],
    assignments: [],
    recommendations: [],
  },
  {
    id: "inc-demo-4",
    title: "Flood Report — Riverfront Area (Possible Duplicate)",
    description: "Citizen report of water overflowing embankment near Usmanpura riverfront walkway.",
    type: "FLOOD",
    severity: "HIGH",
    status: "REPORTED",
    source: "CITIZEN_APP",
    locationName: "Usmanpura Riverfront, Ahmedabad",
    latitude: 23.0456,
    longitude: 72.5721,
    locationConfidence: 0.80,
    affectedCount: 50,
    injuryCount: 2,
    hazards: JSON.stringify(["Fast Currents", "Crowd Congestion"]),
    requiredCapabilities: JSON.stringify(["WATER_RESCUE", "EVACUATION"]),
    language: "gu",
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    events: [],
    assignments: [],
    recommendations: [],
  },
  {
    id: "inc-demo-5",
    title: "Multi-Vehicle Accident — NH48, KM 45",
    description: "Commercial freight truck and passenger bus collision. Lanes partially obstructed.",
    type: "ROAD_ACCIDENT",
    severity: "HIGH",
    status: "IN_PROGRESS",
    source: "RADIO",
    locationName: "NH48 Expressway KM 45, Ahmedabad",
    latitude: 22.8900,
    longitude: 72.6800,
    locationConfidence: 0.92,
    affectedCount: 18,
    injuryCount: 6,
    hazards: JSON.stringify(["Diesel Spill", "Highway Obstruction"]),
    requiredCapabilities: JSON.stringify(["HEAVY_RESCUE", "TRAUMA_CARE", "TRAFFIC_MANAGEMENT"]),
    language: "en",
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    events: [],
    assignments: [],
    recommendations: [],
  },
  {
    id: "inc-demo-6",
    title: "High-Rise Commercial Complex Fire — SG Highway",
    description: "Electrical duct fire on 8th floor. Sprinkler system activated. Building evacuated successfully.",
    type: "FIRE",
    severity: "CRITICAL",
    status: "RESOLVED",
    source: "EMERGENCY_CALL",
    locationName: "SG Highway Commerce Tower, Ahmedabad",
    latitude: 23.0520,
    longitude: 72.5150,
    locationConfidence: 0.99,
    affectedCount: 150,
    injuryCount: 0,
    hazards: JSON.stringify(["Smoke Inhalation"]),
    requiredCapabilities: JSON.stringify(["FIRE_SUPPRESSION", "HIGH_RISE_RESCUE"]),
    language: "en",
    createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    events: [],
    assignments: [],
    recommendations: [],
  },
];

export const FALLBACK_RESOURCES = [
  {
    id: "res-demo-1",
    name: "AMB-001 (Advanced Life Support)",
    type: "AMBULANCE",
    status: "AVAILABLE",
    latitude: 23.0225,
    longitude: 72.5714,
    locationName: "Maninagar Station, Ahmedabad",
    agencyId: "agency-medical",
    agency: { id: "agency-medical", name: "108 Emergency Medical Services", type: "MEDICAL" },
    reliabilityScore: 0.95,
    currentWorkload: 10,
    capabilities: [
      { id: "c-1", capability: "TRAUMA_CARE", equipment: JSON.stringify(["Defibrillator", "Oxygen", "IV Kit"]) },
      { id: "c-2", capability: "PATIENT_TRANSPORT", equipment: JSON.stringify(["Stretcher", "Board"]) },
      { id: "c-3", capability: "ADVANCED_LIFE_SUPPORT", equipment: JSON.stringify(["Ventilator", "Monitor"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-2",
    name: "AMB-002 (Basic Life Support)",
    type: "AMBULANCE",
    status: "AVAILABLE",
    latitude: 23.0096,
    longitude: 72.5040,
    locationName: "Satellite Base, Ahmedabad",
    agencyId: "agency-medical",
    agency: { id: "agency-medical", name: "108 Emergency Medical Services", type: "MEDICAL" },
    reliabilityScore: 0.88,
    currentWorkload: 20,
    capabilities: [
      { id: "c-4", capability: "TRAUMA_CARE", equipment: JSON.stringify(["First Aid Kit", "Oxygen"]) },
      { id: "c-5", capability: "BASIC_LIFE_SUPPORT", equipment: JSON.stringify(["AED", "Oxygen"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-3",
    name: "AMB-003 (Mobile ICU)",
    type: "AMBULANCE",
    status: "DISPATCHED",
    latitude: 23.0500,
    longitude: 72.6100,
    locationName: "Naroda Corridor, Ahmedabad",
    agencyId: "agency-medical",
    agency: { id: "agency-medical", name: "108 Emergency Medical Services", type: "MEDICAL" },
    reliabilityScore: 0.97,
    currentWorkload: 80,
    capabilities: [
      { id: "c-6", capability: "ADVANCED_LIFE_SUPPORT", equipment: JSON.stringify(["ICU Ventilator"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-4",
    name: "NDRF-BOAT-01 (Rigid Inflatable)",
    type: "BOAT",
    status: "AVAILABLE",
    latitude: 23.0300,
    longitude: 72.5800,
    locationName: "Sabarmati Riverfront Depot",
    agencyId: "agency-rescue",
    agency: { id: "agency-rescue", name: "NDRF Battalion 6", type: "RESCUE" },
    reliabilityScore: 0.96,
    currentWorkload: 0,
    capabilities: [
      { id: "c-7", capability: "WATER_RESCUE", equipment: JSON.stringify(["Life Rafts", "Motors", "Tow Lines"]) },
      { id: "c-8", capability: "FLOOD_EVACUATION", equipment: JSON.stringify(["Life Jackets", "Rescue Sleds"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-5",
    name: "NDRF-BOAT-02 (Inflatable Rescue)",
    type: "BOAT",
    status: "AVAILABLE",
    latitude: 23.0350,
    longitude: 72.5850,
    locationName: "Subhash Bridge Depot",
    agencyId: "agency-rescue",
    agency: { id: "agency-rescue", name: "NDRF Battalion 6", type: "RESCUE" },
    reliabilityScore: 0.91,
    currentWorkload: 15,
    capabilities: [
      { id: "c-9", capability: "WATER_RESCUE", equipment: JSON.stringify(["Life Raft", "Sonar"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-6",
    name: "FIRE-ENG-01 (Major Pumper)",
    type: "FIRE_ENGINE",
    status: "AVAILABLE",
    latitude: 23.0250,
    longitude: 72.5600,
    locationName: "Navrangpura Fire Station",
    agencyId: "agency-fire",
    agency: { id: "agency-fire", name: "Ahmedabad Fire & Emergency Services", type: "FIRE" },
    reliabilityScore: 0.94,
    currentWorkload: 0,
    capabilities: [
      { id: "c-10", capability: "FIRE_SUPPRESSION", equipment: JSON.stringify(["Hoses", "Foam System", "Nozzles"]) },
      { id: "c-11", capability: "HEAVY_RESCUE", equipment: JSON.stringify(["Jaws of Life", "Hydraulic Spreader"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-7",
    name: "FIRE-ENG-02 (Water Tender 5000L)",
    type: "FIRE_ENGINE",
    status: "DISPATCHED",
    latitude: 22.9900,
    longitude: 72.6000,
    locationName: "Maninagar Fire Station",
    agencyId: "agency-fire",
    agency: { id: "agency-fire", name: "Ahmedabad Fire & Emergency Services", type: "FIRE" },
    reliabilityScore: 0.90,
    currentWorkload: 75,
    capabilities: [
      { id: "c-12", capability: "FIRE_SUPPRESSION", equipment: JSON.stringify(["5000L Water Tank"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-8",
    name: "POLICE-PATROL-01 (Sector Alpha)",
    type: "POLICE_CAR",
    status: "AVAILABLE",
    latitude: 23.0150,
    longitude: 72.5700,
    locationName: "Ellisbridge Police Station",
    agencyId: "agency-police",
    agency: { id: "agency-police", name: "Ahmedabad City Police", type: "POLICE" },
    reliabilityScore: 0.89,
    currentWorkload: 25,
    capabilities: [
      { id: "c-13", capability: "TRAFFIC_MANAGEMENT", equipment: JSON.stringify(["Spikes", "Flares", "Barricades"]) },
      { id: "c-14", capability: "EVACUATION", equipment: JSON.stringify(["Megaphone", "Emergency Lights"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-9",
    name: "POLICE-PATROL-02 (Sector Beta)",
    type: "POLICE_CAR",
    status: "AVAILABLE",
    latitude: 23.0400,
    longitude: 72.5500,
    locationName: "Vastrapur Police Station",
    agencyId: "agency-police",
    agency: { id: "agency-police", name: "Ahmedabad City Police", type: "POLICE" },
    reliabilityScore: 0.92,
    currentWorkload: 10,
    capabilities: [
      { id: "c-15", capability: "TRAFFIC_MANAGEMENT", equipment: JSON.stringify(["Cones", "Barricades"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-10",
    name: "HAZMAT-01 (Decontamination Mobile)",
    type: "HAZMAT_UNIT",
    status: "STANDBY",
    latitude: 22.9800,
    longitude: 72.5500,
    locationName: "GIDC Industrial Zone Base",
    agencyId: "agency-fire",
    agency: { id: "agency-fire", name: "Ahmedabad Fire & Emergency Services", type: "FIRE" },
    reliabilityScore: 0.93,
    currentWorkload: 0,
    capabilities: [
      { id: "c-16", capability: "HAZMAT_RESPONSE", equipment: JSON.stringify(["Level A Suits", "Gas Detectors"]) },
      { id: "c-17", capability: "DECONTAMINATION", equipment: JSON.stringify(["Decon Showers", "Neutralizers"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-11",
    name: "DRONE-SURV-01 (Thermal Eye)",
    type: "DRONE",
    status: "AVAILABLE",
    latitude: 23.0200,
    longitude: 72.5700,
    locationName: "EOC Rooftop, Ahmedabad",
    agencyId: "agency-state",
    agency: { id: "agency-state", name: "Gujarat State Emergency Management Authority", type: "GOVERNMENT" },
    reliabilityScore: 0.82,
    currentWorkload: 0,
    capabilities: [
      { id: "c-18", capability: "AERIAL_SURVEILLANCE", equipment: JSON.stringify(["4K Camera", "Thermal FLIR"]) },
    ],
    assignments: [],
  },
  {
    id: "res-demo-12",
    name: "AMB-004 (Out of Service / Overhaul)",
    type: "AMBULANCE",
    status: "OUT_OF_SERVICE",
    latitude: 23.0400,
    longitude: 72.5400,
    locationName: "Central Fleet Maintenance Depot",
    agencyId: "agency-medical",
    agency: { id: "agency-medical", name: "108 Emergency Medical Services", type: "MEDICAL" },
    reliabilityScore: 0.60,
    currentWorkload: 100,
    capabilities: [],
    assignments: [],
  },
];

export const FALLBACK_HOSPITALS = [
  {
    id: "hosp-1",
    name: "Ahmedabad Civil Hospital (Asarwa)",
    latitude: 23.0458,
    longitude: 72.5873,
    totalBeds: 2800,
    availableBeds: 340,
    icuBeds: 180,
    availableIcu: 12,
    burnBeds: 40,
    availableBurn: 5,
    hasHelipad: true,
    hasDecon: true,
    oxygenSecured: true,
    status: "NORMAL",
  },
  {
    id: "hosp-2",
    name: "Sardar Vallabhbhai Patel (SVP) Hospital",
    latitude: 23.0228,
    longitude: 72.5800,
    totalBeds: 1500,
    availableBeds: 220,
    icuBeds: 120,
    availableIcu: 24,
    burnBeds: 25,
    availableBurn: 8,
    hasHelipad: true,
    hasDecon: true,
    oxygenSecured: true,
    status: "NORMAL",
  },
  {
    id: "hosp-3",
    name: "Apollo Hospital (Gandhinagar Highway)",
    latitude: 23.0900,
    longitude: 72.5900,
    totalBeds: 400,
    availableBeds: 85,
    icuBeds: 60,
    availableIcu: 8,
    burnBeds: 15,
    availableBurn: 2,
    hasHelipad: true,
    hasDecon: true,
    oxygenSecured: true,
    status: "NORMAL",
  },
  {
    id: "hosp-4",
    name: "Shardaben General Hospital (Saraspur)",
    latitude: 23.0280,
    longitude: 72.6120,
    totalBeds: 650,
    availableBeds: 110,
    icuBeds: 40,
    availableIcu: 6,
    burnBeds: 10,
    availableBurn: 1,
    hasHelipad: false,
    hasDecon: false,
    oxygenSecured: true,
    status: "NORMAL",
  },
];

export const FALLBACK_SHELTERS = [
  { id: "sh-1", name: "Kankaria Community Relief Shelter", latitude: 23.0050, longitude: 72.6000, capacity: 500, occupied: 320, status: "OPEN" },
  { id: "sh-2", name: "Paldi Municipal Community Hall", latitude: 23.0150, longitude: 72.5650, capacity: 300, occupied: 140, status: "OPEN" },
  { id: "sh-3", name: "Naroda Industrial Worker Relief Center", latitude: 23.0650, longitude: 72.6500, capacity: 400, occupied: 280, status: "OPEN" },
];

export const FALLBACK_AUDIT_LOGS = [
  {
    id: "aud-1",
    action: "DISPATCH_RECOMMENDED",
    entity: "DispatchRecommendation",
    entityId: "rec-101",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    user: { name: "Op. Priya Patel" },
  },
  {
    id: "aud-2",
    action: "UNIT_DEPLOYED",
    entity: "Resource",
    entityId: "res-demo-4",
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    user: { name: "Cmdr. Rajesh Sharma" },
  },
  {
    id: "aud-3",
    action: "SEVERITY_ESCALATED",
    entity: "Incident",
    entityId: "inc-demo-2",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    user: { name: "AI Commander" },
  },
  {
    id: "aud-4",
    action: "INCIDENT_VERIFIED",
    entity: "Incident",
    entityId: "inc-demo-3",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    user: { name: "Dispatcher Anil Kumar" },
  },
  {
    id: "aud-5",
    action: "SYSTEM_INITIALIZED",
    entity: "EOC_Metro",
    entityId: "eoc-gujarat-01",
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    user: { name: "Administrator" },
  },
];

export const FALLBACK_DASHBOARD_DATA = {
  incidents: {
    total: 6,
    byStatus: {
      ASSIGNED: 1,
      IN_PROGRESS: 1,
      REPORTED: 2,
      RESOLVED: 1,
      VERIFIED: 1,
      CLOSED: 0,
    },
    active: 5,
  },
  resources: {
    total: 12,
    byStatus: {
      AVAILABLE: 9,
      DISPATCHED: 2,
      STANDBY: 1,
      OUT_OF_SERVICE: 1,
      EN_ROUTE: 0,
      ON_SCENE: 0,
      RETURNING: 0,
    },
    available: 9,
  },
  hospitals: {
    totalBeds: 5350,
    availableBeds: 755,
    occupancyRate: "86.3",
    details: FALLBACK_HOSPITALS,
  },
  shelters: {
    totalCapacity: 1200,
    occupied: 740,
    occupancyRate: "61.7",
    details: FALLBACK_SHELTERS,
  },
  pendingDispatches: 3,
  recentActivity: FALLBACK_AUDIT_LOGS,
};
